### ISSUE TITLE
Proxies

### ISSUE THREAD

**Issue by Kellokes** [Debupt/MidjourneyWrapper#1] opened 2023-04-10 16:14 UTC
Hi debupt, how are you?

First of all, thank you very much to share this code.

In config.json I found a variable called proxy. Why you using proxy to run in the midjourney? Is it because some kind of ban that could be exist?

**Comment by Kellokes** [comment] 2023-04-10 17:06
Another point here: 
The user token, is for user account ou discord bot?

**Comment by Debupt** [comment] 2023-04-11 00:33
1. about proxy, nothing special, I'm in mainland China, discord is banned here, if you can access discord freely, no need for this field
2. user token is the user account, for REST API, we do not need a discord bot

**Comment by Debupt** [comment] 2023-04-11 01:06
btw, I have fix the bug once proxy field not set

**Comment by lordmen99** [comment] 2023-04-11 03:44
any demo online please?

**Comment by Kellokes** [comment] 2023-04-11 13:58
Tkss @Debupt!!

Another thing that I trying to do with your code is get image when concluded. Is it  working fine for you?

**Comment by Debupt** [comment] 2023-04-11 15:41
> any demo online please?

please `python3 example.py` to run the demo

**Comment by lordmen99** [comment] 2023-04-11 15:44
> > any demo online please?
> 
> please `python3 example.py` to run the demo

the problem is i dont have subcription :). maybe u have any some sample please

**Comment by Debupt** [comment] 2023-04-11 15:54
> > > any demo online please?
> > 
> > 
> > please `python3 example.py` to run the demo
> 
> the problem is i dont have subcription :). maybe u have any some sample please

Yeah, first of all, you should have a midjourney discord account

**Comment by Debupt** [comment] 2023-04-11 15:56
> Tkss @Debupt!!
> 
> Another thing that I trying to do with your code is get image when concluded. Is it working fine for you?

I suspect wrong configuration about token, server id or channel id, you could refer README.md to check them

**Comment by Debupt** [comment] 2023-04-15 13:11
I assume you have solved the problem, close this issue

**Closed as completed by Debupt** 2023-04-15 13:11 UTC
